{% extends layouts.frontend %}
{% block title %}Login Page{% endblock %}

{% block content %}
<div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <div>
            <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
            <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900 dark:text-gray-200">
                Sign in to your account
            </h2>
            <p class="mt-2 text-center text-sm text-gray-600">
                <span class="text-gray-600 dark:text-gray-400">Or</span>
                <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500 dark:text-indigo-500 dark:hover:text-indigo-400">
                start your 14-day free trial
                </a>
            </p>
        </div>
        <form action="{{ url('login') }}" method="POST">
            {{ csrf_token() }}
            <div class="py-8 px-8 rounded-xl">
                <div class="my-5 text-sm">
                    {% $email = flash('email') %}
                    <label for="email" class="block text-black dark:text-white">Email</label>
                    <input type="email" autofocus name="email" id="email" class="form-input w-full rounded-2xl px-4 py-2 mt-2 bg-gray-100 text-black dark:bg-gray-700 dark:text-gray-100 border outline-none {{ $email ? 'border-red-500': 'border-gray-200' }}" placeholder="Email" value="{{ old('email') }}" />
                    {{ $email ? "<div id='validationEmail' class='is-invalid-text'>$email</div>" : "" }}
                </div>
                <div class="my-5 text-sm">
                    {% $password = flash('password') %}
                    <label for="password" class="block text-black dark:text-white">Password</label>
                    <input type="password" name="password" id="password" class="form-input w-full rounded-2xl px-4 py-2 mt-2 bg-gray-100 text-black dark:bg-gray-700 dark:text-gray-100 border outline-none {{ $password ? 'border-red-500': 'border-gray-200' }}" placeholder="Password" />
                    {{ $password ? "<div id='validationPassword' class='is-invalid-text'>$password</div>" : "" }}
                </div>
                <div>
                    <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                            <!-- Heroicon name: solid/lock-closed -->
                            <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
                            </svg>
                        </span> Sign in
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}