{% extends layouts.frontend %}
{% block title %}Login Page{% endblock %}

{% block content %}
<div class="flex items-center justify-center px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <div>
            <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
            <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900 dark:text-gray-200">
                Register a new account
            </h2>
        </div>
        <form class="form-row" action="{{ url('register') }}" method="POST">
            {{ csrf_token() }}
            <div class="my-5 text-sm">
                {% $name = flash('name') %}
                <label for="name" class="block text-black dark:text-white">Name or Alias</label>
                <input type="text" class="form-input w-full rounded-lg px-4 py-2 mt-2 bg-gray-100 text-black dark:bg-gray-700 dark:text-gray-100 border-2 outline-none {{ has_error($name) }}" name="name" id="name" placeholder="Name or Alias" value="{{ old('name') }}">
                {{ text_error($name) }}
            </div>
            <div class="my-5 text-sm">
                {% $firstname = flash('firstname') %}
                <label for="firstname" class="block text-black dark:text-white">First Name</label>
                <input type="text" class="form-input w-full rounded-lg px-4 py-2 mt-2 bg-gray-100 text-black dark:bg-gray-700 dark:text-gray-100 border-2 outline-none  {{ has_error($firstname) }}" name="firstname" id="firstname" placeholder="First Name" value="{{ old('firstname') }}">
                {{ text_error($firstname) }}
            </div>
            <div class="my-5 text-sm">
                {% $lastname = flash('lastname') %}
                <label for="lastname" class="block text-black dark:text-white">Last Name</label>
                <input type="text" class="form-input w-full rounded-lg px-4 py-2 mt-2 bg-gray-100 text-black dark:bg-gray-700 dark:text-gray-100 border-2 outline-none {{ has_error($lastname) }}" name="lastname" id="lastname" placeholder="Last Name" value="{{ old('lastname') }}">
                {{ text_error($lastname) }}
            </div>
            <div class="my-5 text-sm">
                {% $email = flash('email') %}
                <label for="email" class="block text-black dark:text-white">Email address</label>
                <input type="email" class="form-input w-full rounded-lg px-4 py-2 mt-2 bg-gray-100 text-black dark:bg-gray-700 dark:text-gray-100 border-2 outline-none {{ has_error($email) }}" name="email" id="email" placeholder="Email address" value="{{ old('email') }}" autocomplete="username">
                {{ text_error($email) ?: "<div class='text-sm font-medium text-blue-500'>We'll never share your email with anyone else.</div>" }}
            </div>
            <div class="my-5 text-sm">
                {% $password = flash('password') %}
                <label for="password" class="block text-black dark:text-white">Password</label>
                <input type="password" class="form-input w-full rounded-lg px-4 py-2 mt-2 bg-gray-100 text-black dark:bg-gray-700 dark:text-gray-100 border-2 outline-none {{ has_error($password) }}" placeholder="password" name="password" id="password" autocomplete="new-password">
                {{ text_error($password) }}
            </div>
            <div class="my-5 text-sm">
                {% $confirm_password = flash('confirm_password') %}
                <label for="confirm_password" class="block text-black dark:text-white">Confirm Password</label>
                <input type="password" class="form-input w-full rounded-lg px-4 py-2 mt-2 bg-gray-100 text-black dark:bg-gray-700 dark:text-gray-100 border-2 outline-none {{ has_error($confirm_password) }}" placeholder="Confirm Password" name="confirm_password" id="confirm_password" autocomplete="new-password">
                {{ text_error($confirm_password) }}
            </div>
            <div class="my-5 text-sm">
                <div>
                    <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
                            </svg>
                        </span> Register
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block styles %}
<style>
    .f-outline input:focus-within ~ label,
    .f-outline input:not(:placeholder-shown) ~ label {
        transform: translateY(-1.5rem) translatex(-1rem) scaleX(0.80) scaleY(0.80);
    }
</style>
{% endblock %}