<nav class="bg-gray-200 dark:bg-gray-700">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
                <a href="{{ route('home') }}" class="flex-shrink-0">
                    <img class="h-8 w-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
                </a>
                <div class="hidden md:block">
                    <div class="ml-10 flex items-baseline space-x-4 text-sm font-medium">
                        <!-- 
                            Current: "text-white dark:text-black", 
                            Default: "text-gray-800 hover:bg-gray-700 hover:text-gray-200 dark:text-gray-200 dark:hover:bg-gray-600 dark:hover:text-gray-200" 
                        -->
                        {% if ( !auth() ): %}
                        <a href="{{ route('home') }}" class="menu menu-current">Home</a>
                        <a href="#" class="menu menu-default">Team</a>
                        <a href="#" class="menu menu-default">Projects</a>
                        <a href="#" class="menu menu-default">Calendar</a>
                        <a href="#" class="menu menu-default">Reports</a>
                        {% else: %}
                        <a href="{{ route('dashboard') }}" class="menu menu-current">Dashboard</a>
                        {% endif; %}
                    </div>
                </div>
            </div>
            <div class="flex-shrink-0 flex items-center">
                <!-- Drak Mode -->
                <div class="flex items-center ml-3">
                    <button type="button" x-on:click="mode=false" x-show="mode" class="setMode" id="sun" x-cloak>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-yellow-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
                        </svg>
                    </button>
                    <button type="button" x-on:click="mode=true" x-show="!mode" class="setMode" id="dark" x-cloak>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-800" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
                        </svg>
                    </button>
                </div>
                <!-- Mobile menu button -->
                <div class="block md:hidden ml-3">
                    <button type="button" class="bg-gray-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" aria-controls="mobile-menu" aria-expanded="false"
                        x-on:click="mobile = !mobile">
                        <span class="sr-only">Open main menu</span>
                        <!--
                            Heroicon name: outline/menu
                            Menu open: "hidden", Menu closed: "block"
                        -->
                        <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        </svg>
                        <!--
                            Heroicon name: outline/x
                            Menu open: "block", Menu closed: "hidden"
                        -->
                        <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>
                {% if ( auth() ): %}
                <!-- Notification bell -->
                <div class="hidden md:block ml-3">
                    <div class="flex items-center">
                        <button class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
                            <span class="sr-only">View notifications</span>
                            <!-- Heroicon name: outline/bell -->
                            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                            </svg>
                        </button>
                    </div>
                </div>
                <!-- Profile dropdown -->
                <div class="hidden md:block ml-3">
                    <div class="flex items-center">
                        <div class="relative" x-data="{open:false}">
                            <div>
                                <button type="button" class="max-w-xs bg-gray-800 rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true" x-on:click="open = !open">
                                    <span class="sr-only">Open user menu</span>
                                    <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                                </button>
                            </div>
                            <!--
                                Dropdown menu, show/hide based on menu state.
                                Entering: "transition ease-out duration-100"
                                From: "transform opacity-0 scale-95"
                                To: "transform opacity-100 scale-100"
                                Leaving: "transition ease-in duration-75"
                                From: "transform opacity-100 scale-100"
                                To: "transform opacity-0 scale-95"
                            -->
                            <div class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white text-gray-700 dark:bg-gray-600 dark:text-white ring-1 ring-black ring-opacity-5 focus:outline-none text-sm" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" x-show="open" x-on:click.away="open = false" x-cloak>
                                <!-- Active: "bg-gray-100", Not Active: "" -->
                                <a href="{{ route('dashboard') }}" class="block px-4 py-2" role="menuitem" tabindex="-1" id="user-menu-item-1">Dashboard</a>
                                <a href="{{ route('settings') }}" class="block px-4 py-2" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
                                <a href="{{ route('profile', auth()->name) }}" class="block px-4 py-2" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
                                <a href="#" class="block px-4 py-2" role="menuitem" tabindex="-1" id="user-menu-item-2" onClick="document.getElementById('logout').submit();">Sign out</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% else: %}
                <!-- Auth links -->
                <div class="hidden md:block ml-3">
                    <div class="flex items-center space-x-4 text-sm font-medium">
                        <a href="{{ route('auth.login') }}" class="menu menu-default">Login</a>
                        <a href="{{ route('auth.register') }}" class="menu menu-default">Register</a>
                    </div>
                </div>
                {% endif; %}
            </div>
        </div>
    </div>
    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="md:hidden absolute w-full dark:bg-gray-800 bg-gray-200 shadow-2xl" id="mobile-menu" x-show="mobile" x-cloak>
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3 text-base font-medium">
            <!-- 
                Current: "bg-gray-900 text-white", 
                Default: "text-gray-800 hover:bg-gray-700 hover:text-gray-200 dark:text-gray-200 dark:hover:bg-gray-600 dark:hover:text-gray-200" 
            -->
            {% if ( !auth() ): %}
            <a href="{{ route('home') }}" class="block menu menu-current">Home</a>
            <a href="#" class="block menu menu-default">Team</a>
            <a href="#" class="block menu menu-default">Projects</a>
            <a href="#" class="block menu menu-default">Calendar</a>
            <a href="#" class="block menu menu-default">Reports</a>
            {% else: %}
            <a href="{{ route('dashboard') }}" class="menu menu-current">Dashboard</a>
            {% endif; %}
        </div>
        <div class="pt-2 pb-3 border-t border-gray-400 dark:border-gray-700">
            {% if ( auth() ): %}
            <div class="flex items-center px-5">
                <div class="flex-shrink-0">
                    <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                </div>
                <div class="ml-3">
                    <div class="text-base font-medium leading-none text-gray-800 dark:text-gray-200">Tom Cook</div>
                    <div class="text-sm font-medium leading-none text-gray-700 dark:text-gray-300">tom@example.com</div>
                </div>
                <button class="ml-auto bg-gray-800 flex-shrink-0 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
                    <span class="sr-only">View notifications</span>
                    <!-- Heroicon name: outline/bell -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                    </svg>
                </button>
            </div>
            <div class="mt-3 px-2 space-y-1 text-base font-medium">
                <a href="{{ route('dashboard') }}" class="block menu menu-default">Dashboard</a>
                <a href="{{ route('settings') }}" class="block menu menu-default">Settings</a>
                <a href="{{ route('profile', auth()->name) }}" class="block menu menu-default">Your Profile</a>
                <a href="#" class="block menu menu-default" onClick="document.getElementById('logout').submit();">Sign out</a>
            </div>
            {% else: %}
            <div class="mt-3 px-2 space-y-1 text-base font-medium">
                <a href="{{ route('auth.login') }}" class="block menu menu-default">Login</a>
                <a href="{{ route('auth.register') }}" class="block menu menu-default">Register</a>
            </div>
            {% endif; %}
        </div>
    </div>
    <form action="{{ route('auth.logout') }}" method="post" id="logout" class="hidden">
        {{ csrf_token() }}
        <button type="submit" class="btn btn-sm btn-danger">Logout</button>
    </form>
</nav>