{% if ( auth() ): %}
    {% extends layouts.backend %}
    {% block title %}Error{% endblock %}
    {% block content-header-title %}Error{% endblock %}
    {% block content-header-subtitle %} Un error ha ocurrido {% endblock %}
{% else: %}
    {% extends layouts.frontend %}
{% endif; %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <strong>{{ $message }}</strong>
</div>
{% endblock %}