{% if ( auth() ): %}
    {% extends layouts.backend %}
    {% block content-header-title %}Error{% endblock %}
    {% block content-header-subtitle %} Un error ha ocurrido {% endblock %}
{% else: %}
    {% extends layouts.frontend %}
{% endif; %}
{% block title %}Error{% endblock %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h2>Error {{$codigo_error}}</h2>
    <p>{{$message_error}}</p>
</div>
{% endblock %}