{% extends layouts.backend %}
{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 dark:text-gray-200 sm:text-4xl">
        <span class="block">Welcome {{ $user->name }}</span>
        <span class="block text-indigo-600 hover:text-indigo-500 dark:text-indigo-500 dark:hover:text-indigo-400">Are yu ready for a new day?</span>
    </h2>
</div>
{% endblock %}