{% extends layouts.responsive %}
{% block title %}Editar usuario{% endblock %}

{% block content %}
<div class="flex justify-between items-center border-t-2 border-green-700 px-2">
    <h2 class="box-title">
        <span class="">Editar usuario</span>
    </h2>
    <div class="flex">
        <a href="{{ route('users.index') }}" class="btn btn-warning">Lista de usuarios</a>
    </div>
</div>
<form action="{{ route('profile.update') }}" method="post" class="flex flex-wrap -mx-1 overflow-hidden border-t-2 dark:border-gray-700 border-gray-200">
    {{ csrf_token() }}
    {{ method_field('PUT') }}
    <div class="my-2 px-2 overflow-hidden w-full lg:w-1/2">
        <!-- Column Content -->
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $name = flash('name') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="name">Name or Alias <span class="dark:text-red-400 text-red-700 font-semibold">*</span></label>
                {{ text_error($name) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($name) }}" type="text" placeholder="Name or Alias" name="name" id="name" value="{{ old('name', $user->name) }}" />
            </div>
        </div>
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $email = flash('email') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="email">Email <span class="dark:text-red-400 text-red-700 font-semibold">*</span></label>
                {{ text_error($email) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($email) }}" type="email" placeholder="Email" name="email" id="email" value="{{ old('email', $user->email) }}" />
            </div>
        </div>
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $role_id = flash('role_id') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="role_id">Seleccione un Role <span class="dark:text-red-400 text-red-700 font-semibold">*</span></label>
                {{ text_error($role_id) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <select class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($role_id) }}" name="role_id" id="role_id">
                    {% foreach( $roles as $role ): %}
                    <option value="{{ $role->id}}" {{ is_selected($role->id, old('role_id', $user->role_id)) }}>{{$role->name}}</option>
                    {% endforeach; %}
                </select>
            </div>
        </div>
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $password = flash('password') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="password">New Password</label>
                {{ text_error($password) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($password) }}" type="password" placeholder="New Password" name="password" id="password" />
            </div>
        </div>
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $confirm_password = flash('confirm_password') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="confirm_password">Confirm Password</label>
                {{ text_error($confirm_password) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($confirm_password) }}" type="password" placeholder="Confirm Password" name="confirm_password" id="confirm_password" />
            </div>
        </div>
    </div>

    <div class="my-2 px-2 overflow-hidden w-full lg:w-1/2">
        <!-- Column Content -->
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $firstname = flash('firstname') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="firstname">Firstname</label>
                {{ text_error($firstname) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($firstname) }}" type="text" placeholder="Firstname" name="firstname" id="firstname" value="{{ old('firstname', $user->profile->firstname) }}" />
            </div>
        </div>
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $lastname = flash('lastname') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="lastname">Lastname</label>
                {{ text_error($lastname) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($lastname) }}" type="text" placeholder="Lastname" name="lastname" id="lastname" value="{{ old('lastname', $user->profile->lastname) }}" />
            </div>
        </div>
    </div>

    <div class="my-2 px-2 overflow-hidden w-full lg:w-1/2">
        <!-- Column Content -->
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center my-2">
            <div class="mb-2 md:mb-0 md:w-1/3"></div>
            <div class="md:w-2/3 md:flex-grow">
                <button class="btn btn-success">Editar Usuario</button>
                <a href="{{ route('users.index') }}"class="btn text-yellow-800 dark:text-yellow-300 float-right">cancelar</a>
            </div>
        </div>
    </div>

</form>

{% endblock %}