{% extends layouts.responsive %}
{% block title %}Perfil usuario{% endblock %}

{% block content %}
<div class="flex justify-between items-center border-t-2 border-green-700 px-2">
    <h2 class="box-title">
        <span class="">Perfil usuario</span>
    </h2>
    <div class="flex">
        <a href="{{ route('dashboard') }}" class="btn btn-warning">Dashboard</a>
    </div>
</div>
<form action="{{ route('profile.update') }}" method="post" enctype="multipart/form-data" class="flex flex-wrap -mx-1 overflow-hidden border-t-2 dark:border-gray-700 border-gray-200 text-sm" autocomplete="off">
    {{ csrf_token() }}
    {{ method_field('PUT') }}
    <div class="my-2 px-2 overflow-hidden w-full lg:w-1/2">
        <!-- Column Content -->
        <div class="md:flex md:items-center my-2">
            {% $name = flash('name') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="name">Name or Alias <span class="dark:text-red-400 text-red-700 font-semibold">*</span></label>
                {{ text_error($name) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($name) }}" type="text" placeholder="Name or Alias" name="name" id="name" value="{{ old('name', $user->name) }}" />
            </div>
        </div>
        <div class="md:flex md:items-center my-2">
            {% $email = flash('email') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="email">Email <span class="dark:text-red-400 text-red-700 font-semibold">*</span></label>
                {{ text_error($email) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($email) }}" type="email" placeholder="Email" name="email" id="email" value="{{ old('email', $user->email) }}" />
            </div>
        </div>
        <div class="md:flex md:items-center my-2">
            {% $role_id = flash('role_id') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="role_id">Seleccione un Role <span class="dark:text-red-400 text-red-700 font-semibold">*</span></label>
                {{ text_error($role_id) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <select class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($role_id) }}" name="role_id" id="role_id">
                    {% foreach( $roles as $role ): %}
                    <option value="{{ $role->id}}" {{ is_selected($role->id, old('role_id', $user->role_id)) }}>{{$role->name}}</option>
                    {% endforeach; %}
                </select>
            </div>
        </div>
        <div class="md:flex md:items-center my-2">
            {% $password = flash('password') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="password">New Password</label>
                {{ text_error($password) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($password) }}" type="password" placeholder="New Password" name="password" id="password" autocomplete="New Password" />
            </div>
        </div>
        <div class="md:flex md:items-center my-2">
            {% $confirm_password = flash('confirm_password') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="confirm_password">Confirm Password</label>
                {{ text_error($confirm_password) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($confirm_password) }}" type="password" placeholder="Confirm Password" name="confirm_password" id="confirm_password" autocomplete="New Password" />
            </div>
        </div>
    </div>

    <div class="my-2 px-2 overflow-hidden w-full lg:w-1/2">
        <!-- Column Content -->
        <div class="md:flex md:items-center my-2">
            {% $firstname = flash('firstname') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="firstname">Firstname</label>
                {{ text_error($firstname) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($firstname) }}" type="text" placeholder="Firstname" name="firstname" id="firstname" value="{{ old('firstname', $user->profile->firstname) }}" />
            </div>
        </div>
        <div class="md:flex md:items-center my-2">
            {% $lastname = flash('lastname') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="lastname">Lastname</label>
                {{ text_error($lastname) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($lastname) }}" type="text" placeholder="Lastname" name="lastname" id="lastname" value="{{ old('lastname', $user->profile->lastname) }}" />
            </div>
        </div>
        <div class="md:flex md:items-center my-4" x-data="imageViewer()">
            <div class="mb-2 md:mb-0 md:w-1/3">
            <span>Imagen de Perfil</span>
            </div>
            <div class="md:w-2/3 flex items-center space-x-2 mb-2 w-full">
                <!-- Show the image -->
                <template x-if="imageUrl">
                    <img :src="imageUrl" class="object-cover rounded-full border dark:border-gray-700 border-gray-200 w-20 h-20 lg:w-24 lg:h-24">
                </template>
                <!-- Show the gray box when image is not available -->
                <template x-if="!imageUrl">
                    <div class="border rounded-full dark:border-gray-700 border-gray-200 bg-gray-100 w-20 h-20 lg:w-24 lg:h-24"></div>
                </template>
                <!-- Image file selector -->
                <div class="flex-1 flex text-center">
                    <!-- <input class="mt-2" type="file" accept="image/*" @change="fileChosen"> -->
                    <div class="flex w-full items-center justify-center bg-grey-lighter">
                        <label class="w-64 flex flex-col items-center px-4 py-6 bg-white hover:bg-blue-200 dark:bg-gray-800 rounded-lg shadow-lg tracking-wide uppercase border dark:border-gray-700 border-gray-200 cursor-pointer text-blue-800 hover:text-blue-600 dark:text-blue-300 dark:hover:text-blue-600">
                            <template x-if="!imageUrl">
                                <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" >
                                    <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
                                </svg>
                            </template>
                            <span class="mt-2 text-xs font-semibold leading-normal" x-text="imageName"></span>
                            <input type='file' class="hidden" name="imagen" id="imagen" accept="image/*" @change="fileChosen" />
                        </label>
                        <template x-if="hasImage">
                            <button type="button" class="btn btn-danger text-xs" @click="fileDelete">x</button>
                        </template>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="my-2 px-2 overflow-hidden w-full lg:w-1/2">
        <!-- Column Content -->
        <div class="md:flex md:items-center my-2">
            <div class="mb-2 md:mb-0 md:w-1/3"></div>
            <div class="md:w-2/3 md:flex-grow">
                <button class="btn btn-success">Editar Usuario</button>
                <a href="{{ route('dashboard') }}"class="btn text-yellow-800 dark:text-yellow-300 float-right">cancelar</a>
            </div>
        </div>
    </div>

</form>
{% endblock %}

{% block scripts %}
<script>
function imageViewer() {
    return {
        imageUrl: '{{ image_profile() }}',
        hasImage: '',
        imageName: 'Ningún archivo seleccionado',

        fileChosen(event) {
            this.fileToDataUrl(event, src => this.imageUrl = src);
            this.hasImage = 'ok';
        },

        fileToDataUrl(event, callback) {
            if (! event.target.files.length) return

            let file = event.target.files[0],
                reader = new FileReader()

            this.imageName = file.name;
            reader.readAsDataURL(file)
            reader.onload = e => callback(e.target.result)
        },

        fileDelete(event) {
            event.preventDefault();
            document.getElementById('imagen').value = null;
            this.imageUrl = '{{ image_profile() }}';
            this.hasImage = '';
            this.imageName = 'Ningún archivo seleccionado';
        }
    }
}
</script>
{% endblock %}