{% extends layouts.responsive %}
{% block title %}Permisos{% endblock %}

{% block content %}
<div class="container mx-auto py-2 flex flex-col border-t-2 border-blue-600">
    <div class="flex items-center justify-between mb-4">
        <h2 class="text-base sm:text-lg text-gray-900 dark:text-gray-200">
            <span class="">Lista de permisos</span>
        </h2>
        <div class="flex"></div>
    </div>
    <div class="flex  mb-4">
        <div class="w-full border-2 border-blue-600 h-64"></div>
    </div>
</div>
{% endblock %}