{% extends layouts.responsive %}
{% block title %}Permisos{% endblock %}

{% block content %}
<div class="flex justify-between items-center border-t-2 border-blue-700 p-2">
    <h2 class="box-title">
        <span class="">Lista de permisos</span>
    </h2>
    <div class="flex">
        <a href="{{ route('permissions.create') }}" class="btn btn-primary">Nuevo permiso</a>
    </div>
</div>
<div class="lex flex-wrap p-2 overflow-hidden border-t-2 dark:border-gray-700 border-gray-200 text-xs">
    <div class="w-full scrollbar-thin scrollbar-thumb-gray-500 scrollbar-track-gray-400 overflow-x-scroll">
        <table class="w-full rounded-lg divide-y divide-gray-400 dark:divide-gray-500 overflow-hidden bg-gray-400 text-gray-900 dark:bg-gray-900 dark:text-gray-200">
            <thead class="text-left">
                <tr>
                    <th class="font-semibold uppercase px-3 py-2">Llave</th>
                    <th class="font-semibold uppercase px-3 py-2">Nombre</th>
                    <th class="font-semibold uppercase px-3 py-2">Descripción</th>
                    <th class="font-semibold uppercase px-3 py-2">Grupo</th>
                    <th class="font-semibold uppercase px-3 py-2">Tipo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="bg-gray-300 text-gray-900 dark:bg-gray-700 dark:text-gray-200 divide-y divide-gray-400 dark:divide-gray-500">
                {% if( !$paginador->getTotalItems() ): %}
                <tr>
                    <td colspan="6" class="font-semibold px-3 py-2 text-center">Sin registros encontrados</td>
                </tr>
                {% else: %}
                    {% foreach( $permissions as $permission ): %}
                    <tr class="dark:hover:bg-gray-600 hover:bg-gray-200">
                        <td class="px-3 py-2"> {{$permission->key}} </td>
                        <td class="px-3 py-2"> {{$permission->name}} </td>
                        <td class="px-3 py-2"> {{$permission->description}} </td>
                        <td class="px-3 py-2"> {{$permission->group}} </td>
                        <td class="px-3 py-2"> {{$permission->type}} </td>
                        <td>
                            <div class="inline-flex">
                                <a href="{{ route('permissions.edit', $permission->key) }}" class="btn btn-success">Editar</a>
                                <a href="{{ route('permissions.delete', $permission->key) }}" class="btn btn-danger">Eliminar</a>
                            </div>
                        </td>
                    </tr>
                    {% endforeach; %}
                {% endif; %}
            </tbody>
        </table>
    </div>
    <div class="w-full p-2">
        {% if( $paginador->getTotalItems() ): %}
            {% include partials.paginator %}
        {% endif; %}
    </div>
</div>
{% endblock %}