{% extends layouts.responsive %}
{% block title %}Permisos{% endblock %}

{% block content %}
<div class="flex flex-col">
    <div class="box box-default">
        <div class="box-header">
            <h2 class="box-title">
                <span class="">Lista de permisos</span>
            </h2>
            <div class="flex">
                <a href="#" class="btn btn-primary">Nuevo permiso</a>
            </div>
        </div>
        <div class="box-body">
            <div class="w-full scrollbar-thin scrollbar-thumb-gray-500 scrollbar-track-gray-400 overflow-x-scroll">
                <table class="w-full rounded-lg divide-y divide-gray-400 dark:divide-gray-500 overflow-hidden bg-gray-400 text-gray-900 dark:bg-gray-900 dark:text-gray-200 text-sm">
                    <thead class="text-left">
                        <tr>
                            <th class="font-semibold uppercase px-3 py-2">Nombre</th>
                            <th class="font-semibold uppercase px-3 py-2">Descripción</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody class="bg-gray-300 text-gray-900 dark:bg-gray-700 dark:text-gray-200 divide-y divide-gray-400 dark:divide-gray-500">
                        <tr class="dark:hover:bg-gray-600 hover:bg-gray-200">
                            <td class="px-3 py-2"> Super Administrador </td>
                            <td class="px-3 py-2"> Lorem ipsum dolor, sit amet consectetur adipisicing elit. </td>
                            <td>
                                <div class="inline-flex">
                                    <a href="#" class="btn btn-success">Editar</a>
                                    <a href="#" class="btn btn-danger">Eliminar</a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2"> Administrador </td>
                            <td class="px-3 py-2"> Perspiciatis suscipit veniam repellat labore veritatis maiores recusandae esse soluta magnam amet quidem itaque magni beatae</td>
                            <td>
                                <div class="inline-flex">
                                    <a href="#" class="btn btn-success">Editar</a>
                                    <a href="#" class="btn btn-danger">Eliminar</a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="px-3 py-2"> Usuario </td>
                            <td class="px-3 py-2"> Lorem ipsum dolor, excepturi tenetur, temporibus facilis. Nostrum, magni. </td>
                            <td>
                                <div class="inline-flex">
                                    <a href="#" class="btn btn-success">Editar</a>
                                    <a href="#" class="btn btn-danger">Eliminar</a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3" class="font-semibold px-3 py-2 text-center">Sin registros encontrados</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="box-footer">
            <div class="">Footer Box</div>
        </div>
    </div>
</div>
{% endblock %}