{% extends layouts.responsive %}
{% block title %}Nuevo Role{% endblock %}

{% block content %}
<div class="flex justify-between items-center border-t-2 border-blue-700 px-2">
    <h2 class="box-title">
        <span class="">Nuevo Role</span>
    </h2>
    <div class="flex">
        <a href="{{ route('roles.index') }}" class="btn btn-warning">Lista de roles</a>
    </div>
</div>
<form action="{{ route('roles.store') }}" method="post" class="flex flex-wrap -mx-1 overflow-hidden border-t-2 dark:border-gray-700 border-gray-200">
    {{ csrf_token() }}
    <div class="my-2 px-2 overflow-hidden w-full lg:w-1/2">
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $key = flash('key') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="key">Llave <span class="dark:text-red-400 text-red-700 font-semibold">*</span></label>
                {{ text_error($key) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($key) }}" type="text" placeholder="Llave" name="key" id="key" value="{{ old('key') }}" />
            </div>
        </div>
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $name = flash('name') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="name">Nombre <span class="dark:text-red-400 text-red-700 font-semibold">*</span></label>
                {{ text_error($name) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <input class="w-full h-10 px-3 bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($name) }}" type="text" placeholder="Nombre" name="name" id="name" value="{{ old('name') }}" />
            </div>
        </div>
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center text-sm my-2">
            {% $description = flash('description') %}
            <div class="mb-2 md:mb-0 md:w-1/3">
                <label for="description">Descripción</label>
                {{ text_error($name) }}
            </div>
            <div class="md:w-2/3 md:flex-grow">
                <textarea name="description" id="description" class="w-full bg-gray-200 text-black dark:bg-gray-700 dark:text-gray-200 border rounded-lg focus:shadow-outline text-sm placeholder-gray-600 dark:placeholder-gray-400 {{ has_error($description) }}" placeholder="Descripción">{{ old('description') }}</textarea>
            </div>
        </div>
        <div class="text-gray-700 dark:text-gray-200 md:flex md:items-center my-2">
            <div class="mb-2 md:mb-0 md:w-1/3"></div>
            <div class="md:w-2/3 md:flex-grow">
                <button class="btn btn-primary">Nuevo Role</button>
                <a href="{{ route('roles.index') }}"class="btn text-yellow-800 dark:text-yellow-300 float-right">cancelar</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}