<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ asset('img/logos/favicon.ico') }}" type="image/x-icon">

    <!-- Tailwind CSS -->
    <link href="{{ asset('css/tailwind.css') }}" rel="stylesheet">

    <style>
        [x-cloak] { display: none; }
    </style>

    <!-- Optional styles -->
    {% yield styles %}

    <title>{% yield title %} | {{ APP_NAME }}</title>
</head>
<body class="flex flex-col h-screen justify-between bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-100"  x-data="{mobile: false, mode: localStorage.theme == 'dark'}">
    <div class="">
        {% include partials.frontend.navbar %}
        <header class="shadow">
            <div class="max-w-7xl mx-auto py-4 px-2 sm:px-4 lg:px-4">
                <h1 class="text-xl font-bold">
                {% yield title %}
                </h1>
            </div>
        </header>
        {% include partials.frontend.messages %}
        <main class="container mb-auto mx-auto p-4">
        {% yield content %}
        </main>
    </div>

    <footer class="flex justify-between items-center p-3">
        <span>{{ APP_NAME }} © 2021 </span>
        <a class="flex items-center" href="//blockpc.cl">
            <img class="h-6 w-6 rounded mr-2" id="footer-logo" src="{{ asset('img/logos/mini-logo.png') }}">
            <span class="text-xs">BlockPC</span>
        </a>
    </footer>

    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="//unpkg.com/alpinejs"></script>
</body>
</html>