<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ asset('img/logos/favicon.ico') }}" type="image/x-icon">

    <!-- Tailwind CSS -->
    <link href="{{ asset('css/tailwind.css') }}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/bce0453467.js" crossorigin="anonymous"></script>

    <style>
        [x-cloak] { display: none; }
    </style>

    <!-- Optional styles -->
    {% yield styles %}

    <title>{% yield title %} | {{ APP_NAME }}</title>
</head>
<body class="overflow-hidden">
    <div class="relative min-h-screen md:flex" x-data="{mobile:false}">
        {% include partials.responsive.navbar %}

        <div class="flex-1 flex flex-col min-h-screen pt-16 -mt-16 md:mt-0 md:pt-0 justify-between scrollbar-thin scrollbar-thumb-gray-500 scrollbar-track-gray-400 overflow-y-scroll bg-white text-gray-800 dark:bg-gray-800 dark:text-gray-200" x-on:click="mobile=false">
            <div class="py-4 px-2 sm:px-4 lg:px-4 border-b-2 dark:border-gray-700 shadow-md flex justify-between items-center">
                <h1 class="text-xl font-bold"> {% yield title %}</h1>
                <span class="text-xs">Desktop</span>
            </div>
            <div class="flex flex-col justify-between mb-auto">
                <div class="flex flex-col">
                    {% include partials.responsive.messages %}
                </div>
                <div class="p-5">
                    {% yield content %}
                </div>
            </div>
            <footer class="flex justify-between items-center p-5 border-t-2 dark:border-gray-700">
                <span>{{ APP_NAME }} © 2021 </span>
                <a class="flex items-center" href="//blockpc.cl">
                    <img class="h-6 w-6 rounded mr-2" id="footer-logo" src="{{ asset('img/logos/mini-logo.png') }}">
                    <span class="text-xs">BlockPC</span>
                </a>
            </footer>
        </div>
    </div>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="//unpkg.com/alpinejs"></script>
</body>
</html>