{% extends layouts.responsive %}
{% block title %}Responsive Page{% endblock %}

{% block content %}
<div class="text-center">
    <h1 class="text-2xl font-medium">Responsive</h1>
    <i class="fas fa-home"></i><span class="text-lg font-bold">{{ APP_NAME }}</span>
    <p class="text-sm font-medium py-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero quia tempora facilis quo, inventore illo? Voluptas rerum vero nobis doloremque repellendus vitae, nemo obcaecati deleniti in sint voluptates eligendi officiis?</p>
</div>
{% endblock %}